export const codeGtag = `
export const GA_TRACKING_ID: string = process.env.NEXT_PUBLIC_GOOGLE_ID as string;

export const pageview = (url: string): void => {
  (window as any).gtag("config", GA_TRACKING_ID, {
    page_path: url,
  });
};

interface Props {
  action: string;
  category: string;
  label: string;
  value: number;
}

export const event = ({ action, category, label, value }: Props): void => {
  (window as any).gtag("event", action, {
    event_category: category,
    event_label: label,
    value: value,
  });
};
`

export const codeGoogleAnalytics = `
'use client'

import Script from "next/script"
import * as gtag from "../gtag"
const GoogleAnalytics = () => {

    //You can show in the console the GA_TRACKING_ID to confirm
    console.log(gtag.GA_TRACKING_ID)
    return (
        <>
            <Script
                strategy="afterInteractive"
                src={\`https://www.googletagmanager.com/gtag/js?id=\${gtag.GA_TRACKING_ID}\`}
            />
            <Script
                id="gtag-init"
                strategy="afterInteractive"
                dangerouslySetInnerHTML={{
                    __html:\`
                      window.dataLayer = window.dataLayer || [];
                      function gtag(){dataLayer.push(arguments);}
                      gtag('js', new Date());
                      gtag('config', '\${gtag.GA_TRACKING_ID}', {
                      page_path: window.location.pathname,
                      });
                    \`,
                }}
            />
        </>
    )
}

export default GoogleAnalytics
`

export const codeLayout = `
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GoogleAnalytics from "@/components/GoogleAnalytics";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <GoogleAnalytics />
    </body>
    </html>
  );
}


`